### ISSUE TITLE
io.netty version mismatch

### ISSUE THREAD

**Issue by NeilMenne** [alaisi/postgres.async#20]
It seems that the new version of [aleph](https://clojars.org/aleph/versions/0.4.1) and the current version of the underlying [postgres-async-driver](https://github.com/alaisi/postgres-async-driver/blob/master/pom.xml#L74) have a mismatch on io.netty. They also appear to be violently incompatible.

Would it be possible to bump the dependency? When I have some slack time I will investigate myself, but you might be able to answer this question a lot faster.

**Comment by alaisi** [comment]
Upgrading the dependency in postgres-async-driver sounds fine. I should get a release out in a day or two.

**Comment by NeilMenne** [comment]
Thanks!

**Comment by alaisi** [comment]
FYI, I'm waiting for 4.1.0 Final to be released which should be "any day now".

**Comment by niwinz** [comment]
@alaisi 4.1.0.Final is already out
