### ISSUE TITLE
Error rolling back transaction

### ISSUE THREAD

**Issue by donbonifacio** [alaisi/postgres.async#24]
Hello,

Every time I try to rollback a transaction I get the following exception. Commit always work. I'm saying every time but on this specific scenario I did a begin, no other operation, and a rollback. Don't know if that makes a difference.

```
#error {
 :cause com.github.pgasync.impl.netty.NettyPgProtocolStream$ChannelError cannot be cast to com.github.pgasync.Transaction
 :via
 [{:type java.lang.ClassCastException
   :message com.github.pgasync.impl.netty.NettyPgProtocolStream$ChannelError cannot be cast to com.github.pgasync.Transaction
   :at [postgres.async$rollback_BANG_ invokeStatic async.clj 109]}]
 :trace
 [[postgres.async$rollback_BANG_ invokeStatic async.clj 109]
  [postgres.async$rollback_BANG_ invoke async.clj 109]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invokeStatic core.clj 646]
  [clojure.core$apply invoke core.clj 641]
  [postgres.async.impl$result_chan invokeStatic impl.clj 17]
  [postgres.async.impl$result_chan doInvoke impl.clj 12]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [postgres.async$rollback_BANG_ invokeStatic async.clj 112]
  [postgres.async$rollback_BANG_ invoke async.clj 109]
```

**Comment by alaisi** [comment]
Hi,

thanks for the bug report. Can you provide a test case, I'm unable to reproduce this?

```clojure
(testing "rollback! should roll back current transaction"
    (let [tx (<!! (begin! *db*))
          _ (is (instance? Transaction tx))
          rolled-back (<!! (rollback! tx))]
      (is (= true rolled-back))))

;; 0 failures, 0 errors.
```

**Comment by donbonifacio** [comment]
Hum... I tried that example on our wrapper lib and it worked. The only difference to the actual app, is that the app used aleph and we exclude the driver's netty version. All works fine, but this rollback has that weird behaviour.

Maybe #20 will fix this? Is there any prevision on when you're having a new release? Can I test this scenario with the development branch?

**Comment by donbonifacio** [comment]
Well I actually tried aleph `0.4.1`  on the lib and everything worked... so I'm a bit lost. I tried to println the error and I got: 

```
#error {
 :cause "Connection refused: localhost/127.0.0.1:5432"
 :via
 [{:type com.github.pgasync.impl.netty.NettyPgProtocolStream$ChannelError
   :message "java.net.ConnectException: Connection refused: localhost/127.0.0.1:5432"
   :at [com.github.pgasync.impl.netty.NettyPgProtocolStream lambda$connect$25 "NettyPgProtocolStream.java" 66]}
  {:type java.net.ConnectException
   :message "Connection refused: localhost/127.0.0.1:5432"
   :at [sun.nio.ch.SocketChannelImpl checkConnect "SocketChannelImpl.java" -2]}]
```

This makes sense because my server is not at `127.0.0.1:5432`, I really don't know where did it get it. I'm still trying to figure this out.

**Comment by alaisi** [comment]
Also you probably have a bug in the wrapper where you are calling begin! and reading from the channel without checking if the value is a Throwable. Hence the original classcastexception.

**Comment by donbonifacio** [comment]
That was it... thanks for all your *help* @alaisi :)
