### ISSUE TITLE
Parameters as ?

### ISSUE THREAD

**Issue by donbonifacio** [alaisi/postgres.async#25]
Hello,

Is it possible to use parameters with `?` instead of `$1`? I tried but I always get an error. If this was possible, I could use something like [honeysql](https://github.com/jkk/honeysql).

**Comment by alaisi** [comment]
Hi,

the question mark as placeholder is jdbc-specific, postgres doesn't support that. I'd suggest just wrapping the query building (such as honeysql) with a function that does the replacement.

This is for example how the hugsql adapter for postgres.async works: https://gitlab.com/robin.heggelund/hugsql-postgres-async/blob/master/src/hugsql/adapter/postgres_async.clj#L10

**Comment by donbonifacio** [comment]
Thanks for the explanation. :)
