### ISSUE TITLE
add upsert?

### ISSUE THREAD

**Issue by sbaxter** [alaisi/postgres.async#7]
I'm using pg.async to perform async upsert statements [via writeable cte](http://stackoverflow.com/questions/1109061/insert-on-duplicate-update-in-postgresql/8702291#8702291). Not a standard postgres op, so I understand any reluctance to incorporate into pg.async. If there is any interest, though, I'll work on a PR.

My current concoction works like so:
```clojure
(<!! (<upsert! db {:table "users" :where [:id]} {:id 1001 :price 6}))
```

**Comment by alaisi** [comment]
Hi,

my understanding is that native upsert is being worked on in postgres core. So I'd wait for that, but it would be great of you could add your implementation to the project [wiki](https://github.com/alaisi/postgres.async/wiki)
